# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogCli < Formula
  desc "Read-only CLI for querying Datadog APIs"
  homepage "https://github.com/roboalchemist/datadog-cli"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_darwin_amd64.tar.gz"
      sha256 "4f0c53d6376bd3acf4a9e55d1a5db2bd969872b8f5b9836e4bbe8ebe12d0b8a4"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_darwin_arm64.tar.gz"
      sha256 "b0daeb684ba899c5dd87ed7244ae2d2923b52c50f030e655d3b7b39d219a18a1"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_linux_amd64.tar.gz"
      sha256 "30452533cee121b6e360d005b5cb27cc5f2ef9999ae26cd9499f576af22bdfe4"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_linux_arm64.tar.gz"
      sha256 "049e83d2df73ecb55c7a6b8aaf046cc20ff2bbf8dea7e6e2c5805339c370ce66"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  test do
    system "#{bin}/datadog-cli", "--version"
  end
end
