# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogCli < Formula
  desc "Read-only CLI for querying Datadog APIs"
  homepage "https://github.com/roboalchemist/datadog-cli"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.10/datadog-cli_0.1.10_darwin_amd64.tar.gz"
      sha256 "7321b68217f8c8680057642571178fd76384f322dca66522fdd6081dfbbb4ea9"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.10/datadog-cli_0.1.10_darwin_arm64.tar.gz"
      sha256 "596d9f4211856769a5ee24be3763fa1debb33fb203227dbd5b602dd9dfab4120"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.10/datadog-cli_0.1.10_linux_amd64.tar.gz"
      sha256 "62827f444c5b9765c840d5b5e0560723e07434a084e7fd8616ce8b33213e723d"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.10/datadog-cli_0.1.10_linux_arm64.tar.gz"
      sha256 "263938605d13bd9e5aa4c44a6c8a8eef2b6389ed182576ec1e7746f0ccb8bb33"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  test do
    system "#{bin}/datadog-cli", "--version"
  end
end
