# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogCli < Formula
  desc "Read-only CLI for querying Datadog APIs"
  homepage "https://github.com/roboalchemist/datadog-cli"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.9/datadog-cli_0.1.9_darwin_amd64.tar.gz"
      sha256 "a7f56ce8886c8d087cedd82cade3f02e8d30c9b6dc4b11d93bfc373145f80e4e"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.9/datadog-cli_0.1.9_darwin_arm64.tar.gz"
      sha256 "8c8143f7325deeced9e0d47ffed73aad59acf0276767cb2ea835d9fe474789e0"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.9/datadog-cli_0.1.9_linux_amd64.tar.gz"
      sha256 "d47dc018a79442b94fe6ee54f9852d64fffc730e0256e980461f9aab8c3dba2b"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.9/datadog-cli_0.1.9_linux_arm64.tar.gz"
      sha256 "d1550b759da31c700c8a58f65e4b149ca971ee38c176cffe86a15d13b1947e83"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  test do
    system "#{bin}/datadog-cli", "--version"
  end
end
