# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsgenieCli < Formula
  desc "CLI for the OpsGenie REST API v2"
  homepage "https://github.com/roboalchemist/opsgenie-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.1/opsgenie-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "b55c501b92922451096df515188a4ca78d72349df8cb6617d78191b4d7d62ef0"

      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.1/opsgenie-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "8f87a5522ea48cb02fa04f3addebd56e70b86e94cc47fd824ad45e543bb44bc3"

      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.1/opsgenie-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "82a31daf22ac6f48805a05d3df6a7ad337dc569bab3c461c95c5eeb574c383a8"
      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.1/opsgenie-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "61b502135b7af28ee47f9f53d038e220867db9b17cd5c5c6c694dfa515fd41fc"
      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
  end

  test do
    system "#{bin}/opsgenie-cli", "--version"
  end
end
