# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuildbuddyCli < Formula
  desc "CLI for the BuildBuddy Enterprise API"
  homepage "https://github.com/roboalchemist/buildbuddy-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/buildbuddy-cli/releases/download/v0.1.0/buildbuddy-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "f54a1edd31e02cc92beef3041fbd42e89d364f5877b70a207b0850a752e73da9"

      def install
        bin.install "buildbuddy-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/buildbuddy-cli/releases/download/v0.1.0/buildbuddy-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "fbe2e1657fb2854296309d1e571696d4450c6fc376f01dafef5d02e303299f17"

      def install
        bin.install "buildbuddy-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/buildbuddy-cli/releases/download/v0.1.0/buildbuddy-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "202070d9d94127ae856ec80663e904b403db90680ae8cfdafe9af8d58a1c5a16"
      def install
        bin.install "buildbuddy-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/buildbuddy-cli/releases/download/v0.1.0/buildbuddy-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "09db30f66e8ebdfa6eaf8e066f91506889a0222b0d13a8ce59ad18f0a06281ac"
      def install
        bin.install "buildbuddy-cli"
      end
    end
  end
end
