# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogCli < Formula
  desc "Read-only CLI for querying Datadog APIs"
  homepage "https://github.com/roboalchemist/datadog-cli"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_darwin_amd64.tar.gz"
      sha256 "9ff23ae330756405f7a1c4269e5fabfb1db4ad456803a70410868955136c0ff2"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_darwin_arm64.tar.gz"
      sha256 "ee320592b8f39fbc973471cb73922d6cf5a4df4d98a7950128278d9440bc2a17"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_linux_amd64.tar.gz"
      sha256 "5762a7bcf2c3c043fa078cf04ecb3c1f94579cfb53e7dfa8c1c6cd8b28435146"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.11/datadog-cli_0.1.11_linux_arm64.tar.gz"
      sha256 "aa0d93fa580b9cea4ba33f18cc9d4a035f359103bf0ee2b2aaf3986a5e4514d4"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  test do
    system "#{bin}/datadog-cli", "--version"
  end
end
