# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogCli < Formula
  desc "Read-only CLI for querying Datadog APIs"
  homepage "https://github.com/roboalchemist/datadog-cli"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.12/datadog-cli_0.1.12_darwin_amd64.tar.gz"
      sha256 "e2a2edec772592677ea681e7d6d2a0acd225e0b842f741a112702b33d5e04ea5"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.12/datadog-cli_0.1.12_darwin_arm64.tar.gz"
      sha256 "2dc46b30db3d1808e4433a50604cd806a59c0f4cd012eaf540f4f890a7b889f6"

      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.12/datadog-cli_0.1.12_linux_amd64.tar.gz"
      sha256 "3c1b4e13e85b8e452b2cb1b1adbc6f279db42081e2894df7c5603d00dd9ca2b6"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/datadog-cli/releases/download/v0.1.12/datadog-cli_0.1.12_linux_arm64.tar.gz"
      sha256 "2ad82b4398f254c729a7845b7e3d9815a41e3fc6981b5ca2e967c807ef1e43ab"
      define_method(:install) do
        bin.install "datadog-cli"
      end
    end
  end

  test do
    system "#{bin}/datadog-cli", "--version"
  end
end
