# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExaCli < Formula
  desc "CLI for the Exa AI search API"
  homepage "https://github.com/roboalchemist/exa-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "bd467fc59c94715f335e1095e1d07fe1f1655d6985ef32265e3bf911593a7e32"

      def install
        bin.install "exa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "b91b6c92e005de3bd9be39db3df00b52be13dafc85026c4b91ed2e26e1608b01"

      def install
        bin.install "exa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "6b707decf0813103701481d202dfe2b870239d0895035403c57795d01e6d0e5a"
      def install
        bin.install "exa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "aa274b03dea208db0db21a8219e8d3935f8879852586c7ace4e939fa1bbc4108"
      def install
        bin.install "exa"
      end
    end
  end
end
