# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExaCli < Formula
  desc "CLI for the Exa AI search API"
  homepage "https://github.com/roboalchemist/exa-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "6558190147782f0dba14b668058ea7759047cd60965f0420252a6758fadb131f"

      def install
        bin.install "exa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "630bfe9b51983e3b8f01f673f617780adfa3cc9ff0823668653a39b3258f416d"

      def install
        bin.install "exa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "079861e57ad8c02286889689e1358692a6319792d76d75d1a477683faabca8cc"
      def install
        bin.install "exa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/exa-cli/releases/download/v0.1.1/exa-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "b353851bf75bc3dc4f1a5cffbd4cb304c82977e815c80208b47fa4c9924ab7b3"
      def install
        bin.install "exa"
      end
    end
  end
end
