# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FreshrssCli < Formula
  desc "CLI for FreshRSS feed management via Google Reader API"
  homepage "https://github.com/roboalchemist/freshrss-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.0/freshrss-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "db3c49e8cd4e43588bc15bf5d7d436ca62289c46383f442f8ddcf200b1179024"

      def install
        bin.install "freshrss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.0/freshrss-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "9f09303216e47131e38991260efe30a241aec1b3410118769adf7dd1ae2d3851"

      def install
        bin.install "freshrss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.0/freshrss-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "0f7782ea9a5bc03936033e284c29cd3ff0b5e300dc12929b5a47650dda824f90"
      def install
        bin.install "freshrss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.0/freshrss-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "55d38709ea1c758de8efedabbcad9eb4545c02d8b040450b49ec62e07570a700"
      def install
        bin.install "freshrss"
      end
    end
  end
end
