# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FreshrssCli < Formula
  desc "CLI for FreshRSS feed management via Google Reader API"
  homepage "https://github.com/roboalchemist/freshrss-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.1/freshrss-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "d4efd24e6a0bd760a10d6634b72c1a3bd53acab9e095c1ac77fc527bef9b0801"

      def install
        bin.install "freshrss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.1/freshrss-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "71b96b52cdbd771379781faa3503a095981beb33871eab6de0819c654a5922cd"

      def install
        bin.install "freshrss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.1/freshrss-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "6a97469f5c364d7e426067448d268b0b8ad636b332040f2f1b18d79b41165d0a"
      def install
        bin.install "freshrss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/freshrss-cli/releases/download/v0.1.1/freshrss-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "81bc69ae6211f1eb648f27556ed636ae5b6a63322d5b7759659395c37789201b"
      def install
        bin.install "freshrss"
      end
    end
  end
end
