# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KvmCli < Formula
  desc "Agent-first CLI for GL.iNet / PiKVM remote KVMs, VNC, and RustDesk"
  homepage "https://github.com/roboalchemist/kvm-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.0/kvm-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "58692acad94f80191f4aca3a6bd018babef0a3fd7ebbd98060690d8916329616"

      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.0/kvm-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "cc5dd166515e16b229871cf19f46505a0947da5582b39ec4f00e969649daeaa6"

      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.0/kvm-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "bc2cc64fd5d9b5d06a08d46399fcf1c3a3f09d219924553e6be96819a0a8a0d5"
      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.0/kvm-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "f2b429eb9ea9ec4467cfe170759d65504a3c5a54ab4f19e9d8072d9c0619a682"
      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
  end

  test do
    system "#{bin}/kvm-cli", "version"
  end
end
