# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KvmCli < Formula
  desc "Agent-first CLI for GL.iNet / PiKVM remote KVMs, VNC, and RustDesk"
  homepage "https://github.com/roboalchemist/kvm-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.1/kvm-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "30b455459433dd2e1a0e295183fb5f0f02a1670850d96a86342af1d7e3958cc9"

      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.1/kvm-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "924f34d3c4bc65680cd73fb75fa0f48bd9edb6d4fa4a45f60e63168ae0aab183"

      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.1/kvm-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "35cab19e6ee20093ac1501ae24daa014c42c82a18475bb2134e273de8695a114"
      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/kvm-cli/releases/download/v0.4.1/kvm-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "ff3d5a47c11f1edff363d66c522ec8cd694a59cbce68fafd2ba13825380e0a75"
      define_method(:install) do
        bin.install "kvm-cli"
      end
    end
  end

  test do
    system "#{bin}/kvm-cli", "version"
  end
end
