# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsgenieCli < Formula
  desc "CLI for the OpsGenie REST API v2"
  homepage "https://github.com/roboalchemist/opsgenie-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.3/opsgenie-cli_0.2.3_darwin_amd64.tar.gz"
      sha256 "3a6eda847ed791f297a78636c7bc7cdda1c619aaac398a7c1f9c14fa9ff2ece6"

      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.3/opsgenie-cli_0.2.3_darwin_arm64.tar.gz"
      sha256 "1db05a40b8a9510735b647e71f3f915ecd9e23a174b35307ee843a6721b396ec"

      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.3/opsgenie-cli_0.2.3_linux_amd64.tar.gz"
      sha256 "815a9a8ffb7fc4d2da21dcedbaae3ea512a379fa11decaf55a12412f001efbed"
      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/opsgenie-cli/releases/download/v0.2.3/opsgenie-cli_0.2.3_linux_arm64.tar.gz"
      sha256 "b7acc42a4e562445eecc7cae9b4c99c7f74a3754748d492677ff16fcfcb2e679"
      define_method(:install) do
        bin.install "opsgenie-cli"
      end
    end
  end

  test do
    system "#{bin}/opsgenie-cli", "--version"
  end
end
