# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfc < Formula
  desc "CLI for Terraform Cloud (HCP Terraform) API"
  homepage "https://gitea.roboalch.com/roboalchemist/tfc"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roboalchemist/tfc/releases/download/v0.2.1/tfc_0.2.1_darwin_amd64.tar.gz"
      sha256 "022483324663d879138fe62cb313192c282a4913ea42ffd02a50d0ca6489f04c"

      define_method(:install) do
        bin.install "tfc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roboalchemist/tfc/releases/download/v0.2.1/tfc_0.2.1_darwin_arm64.tar.gz"
      sha256 "2ce5cc067af2eca4aaa122c4ef251ff6fe8ba30cce5982ef27cd6d08e57a337b"

      define_method(:install) do
        bin.install "tfc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/tfc/releases/download/v0.2.1/tfc_0.2.1_linux_amd64.tar.gz"
      sha256 "37a6cfaaa7d95f8a5be094cc902fd7be21bc10908afc9f5ce40b26df4d9c4e7f"
      define_method(:install) do
        bin.install "tfc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roboalchemist/tfc/releases/download/v0.2.1/tfc_0.2.1_linux_arm64.tar.gz"
      sha256 "55a5ae5730bd7189ff66e8c21cf53eef43519a37287fd1c5c80ab3268620e8b4"
      define_method(:install) do
        bin.install "tfc"
      end
    end
  end
end
